name: UserWarps
authors:
  - Justin_SGD
version: 1.0.0-SNAPSHOT
main: com.jubyte.userwarps.UserWarps
api-version: 1.13
commands:
  swarp:
    description: 'Test'
  swarpadmin:
    description: 'Test'
